name: Build App Bundle

on:
  push:
    branches: 
      - 'main'
    paths: 
      - './app.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install EAS Cli
        id: install-eas-cli
        run: npm run -g eas-cli

      - name: EAS Build
        id: eas-build
        run: eas build -p android